# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f89034895c31aff13939a261410cb62333d30fa59fc98a9dca476358a2fcd613b2d785f4b58605593ab4d77f38321c6f9d8a4580fec5fd8d03d323b37248d04

test:
  secret_key_base: baa9890f4384222feaadc3c2ad7817cf92942e58c8b6154f46332c5a901541272b0fc2481a582e28267c2863b6d26bc9689e91667765db403891cf5c30095e68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
